### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Lxzjy1** [EricWiener/point-cloud-de-noising#2]
'./tb_logs/WeatherNet/version_1/checkpoints/epoch=4-step=4.ckpt   where?

**Comment by EricWiener** [comment]
You can train the model via `model = WeatherNet()` and skip the block that attempts to load from a checkpoint (this is provided for reference on how to load a checkpoint). Once you have trained the model, you will be able to find the checkpoints in the `tb_logs` directory and then can use the provided cell to load from that checkpoint.

**Comment by Lxzjy1** [comment]
谢谢 我运行训练代码一直出现  RuntimeError: PointCloudDataModule is not attached to a `Trainer`.

**Comment by EricWiener** [comment]
Can you please provide more details about what cell you saw this in and what sequence of cells you ran?

**Comment by Lxzjy1** [comment]
运行训练程序，无法正常训练 LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type      | Params
-----------------------------------------
0 | lila1      | LiLaBlock | 49.3 K
1 | lila2      | LiLaBlock | 804 K 
2 | lila3      | LiLaBlock | 2.2 M 
3 | lila4      | LiLaBlock | 4.2 M 
4 | dropout    | Dropout2d | 0     
5 | lila5      | LiLaBlock | 2.0 M 
6 | classifier | Conv2d    | 387   
-----------------------------------------
9.3 M     Trainable params
0         Non-trainable params
9.3 M     Total params
37.257    Total estimated model params size (MB)
Traceback (most recent call last):
  File "C:\Users\lx\OneDrive\桌面\恶劣Lidar\point-cloud-de-noising-master\meishayong.py", line 32, in <module>
    trainer.fit(model, data_module)
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 990, in _run
    results = self._run_stage()
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 194, in run
    self.setup_data()
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 222, in setup_data
    train_dataloader = _request_dataloader(source)
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 306, in dataloader
    return call._call_lightning_module_hook(self.instance.trainer, self.name, pl_module=self.instance)
  File "C:\Pytorch\envs\pytorch\lib\site-packages\pytorch_lightning\core\module.py", line 208, in trainer
    raise RuntimeError(f"{self.__class__.__qualname__} is not attached to a `Trainer`.")
RuntimeError: PointCloudDataModule is not attached to a `Trainer`.

**Comment by Lxzjy1** [comment]
我的训练过程 不显示损失怎么回事 

Epoch 0:  29%|██▉       | 913/3146 [02:03<05:01,  7.42it/s, v_num=23]
